// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v5.28.3
// source: common.proto

/* eslint-disable */

export const protobufPackage = "common";

export enum RequestStatus {
  Success = 0,
  Failed = 1,
  UNRECOGNIZED = -1,
}

export interface ErrorResponse {
  code: number;
  message: string;
}

export const COMMON_PACKAGE_NAME = "common";
